var products_list = [
  {
    name: "Cotton White Underwear Block Out Edition",
    image: "https://themesflat.com/html/modaz/images/shop/sh-4/1.jpg",
    multiple_colors: true,
    special: "",
    current_price: "19.00",
    old_price: "",
  },
  {
    name: "Cotton White Underwear Block Out Edition",
    image: "https://themesflat.com/html/modaz/images/shop/sh-4/2.jpg",
    multiple_colors: false,
    special: "new",
    current_price: "10.00",
    old_price: "",
  },
  {
    name: "Cotton White Underwear Block Out Edition",
    image: "https://themesflat.com/html/modaz/images/shop/sh-4/3.jpg",
    multiple_colors: false,
    special: "",
    current_price: "20.00",
    old_price: "",
  },
  {
    name: "Cotton White Underwear Block Out Edition",
    image: "https://themesflat.com/html/modaz/images/shop/sh-4/4.jpg",
    multiple_colors: true,
    special: "sale",
    current_price: "60.00",
    old_price: "90.00",
  },
  {
    name: "Cotton White Underwear Block Out Edition",
    image: "https://themesflat.com/html/modaz/images/shop/sh-4/5.jpg",
    multiple_colors: false,
    special: "new",
    current_price: "139.00",
    old_price: "",
  },
  {
    name: "Cotton White Underwear Block Out Edition",
    image: "https://themesflat.com/html/modaz/images/shop/sh-4/6.jpg",
    multiple_colors: true,
    special: "sale",
    current_price: "120.00",
    old_price: "150.00",
  },
  {
    name: "Cotton White Underwear Block Out Edition",
    image: "https://themesflat.com/html/modaz/images/shop/sh-4/7.jpg",
    multiple_colors: false,
    special: "",
    current_price: "110.00",
    old_price: "",
  },
  {
    name: "Cotton White Underwear Block Out Edition",
    image: "https://themesflat.com/html/modaz/images/shop/sh-4/8.jpg",
    multiple_colors: false,
    special: "new",
    current_price: "90.00",
    old_price: "",
  },
  {
    name: "Cotton White Underwear Block Out Edition",
    image: "https://themesflat.com/html/modaz/images/shop/sh-4/9.jpg",
    multiple_colors: false,
    special: "new",
    current_price: "79.00",
    old_price: "",
  },
  {
    name: "Cotton White Underwear Block Out Edition",
    image: "https://themesflat.com/html/modaz/images/shop/sh-4/10.jpg",
    multiple_colors: true,
    special: "new",
    current_price: "120.00",
    old_price: "150.00",
  },
  {
    name: "Cotton White Underwear Block Out Edition",
    image: "https://themesflat.com/html/modaz/images/shop/sh-4/11.jpg",
    multiple_colors: false,
    special: "",
    current_price: "66.00",
    old_price: "",
  },
  {
    name: "Cotton White Underwear Block Out Edition",
    image: "https://themesflat.com/html/modaz/images/shop/sh-4/12.jpg",
    multiple_colors: false,
    special: "new",
    current_price: "20.00",
    old_price: "",
  },
];
